version: "3.3"
services:
  ycontroller:
    build:
      context: .
      dockerfile: Dockerfile
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
      - "/dev/ttyACM1:/dev/ttyACM1"
      - "/dev/ttyACM2:/dev/ttyACM2"
      - "/dev/ttyACM3:/dev/ttyACM3"
      - "/dev/ttyACM4:/dev/ttyACM4"
      - "/dev/ttyACM5:/dev/ttyACM5"
      - "/dev/ttyACM6:/dev/ttyACM6"
      - "/dev/ttyACM7:/dev/ttyACM7"
      - "/dev/ttyACM8:/dev/ttyACM8"
      - "/dev/ttyACM9:/dev/ttyACM9"
      - "/dev/ttyACM10:/dev/ttyACM10"
      - "/dev/ttyACM11:/dev/ttyACM11"
      - "/dev/ttyACM12:/dev/ttyACM12"
      - "/dev/ttyACM13:/dev/ttyACM13"
      - "/dev/ttyACM14:/dev/ttyACM14"
      - "/dev/ttyACM15:/dev/ttyACM15"
    volumes:
      - "/dev/arena:/dev/arena"
    restart: unless-stopped
    pid: "host"
    network_mode: "host"
    command: ["ros2", "launch", "y_arena_valve_controller", "controller.launch.py"]
